/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/macro/AppBar.vue')['default']
    AppDrawer: typeof import('./src/components/macro/AppDrawer.vue')['default']
    BottomNavigation: typeof import('./src/components/macro/BottomNavigation.vue')['default']
    BurgerIcon: typeof import('./src/components/icons/BurgerIcon.vue')['default']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    GameCard: typeof import('./src/components/macro/game/GameCard.vue')['default']
    GameHeaderSection: typeof import('./src/components/macro/game/GameHeaderSection.vue')['default']
    GameIcon: typeof import('./src/components/icons/GameIcon.vue')['default']
    GameListSection: typeof import('./src/components/macro/game/GameListSection.vue')['default']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    InputTextField: typeof import('./src/components/micro/InputTextField.vue')['default']
    LoginDialog: typeof import('./src/components/macro/LoginDialog.vue')['default']
    LogoIcon: typeof import('./src/components/icons/LogoIcon.vue')['default']
    MobileLayout: typeof import('./src/components/layouts/MobileLayout.vue')['default']
    OIcon: typeof import('./src/components/icons/OIcon.vue')['default']
    ProfileIcon: typeof import('./src/components/icons/ProfileIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanIcon: typeof import('./src/components/icons/ScanIcon.vue')['default']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    TicTacToeIcon: typeof import('./src/components/icons/TicTacToeIcon.vue')['default']
    TopUpIcon: typeof import('./src/components/icons/TopUpIcon.vue')['default']
    TransactionIcon: typeof import('./src/components/icons/TransactionIcon.vue')['default']
    XIcon: typeof import('./src/components/icons/XIcon.vue')['default']
  }
}
